{
 "title": "Falco Talon",
 "tags": [
  "falco",
  "security",
  "kubernetes"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "source",
    "label": "source (match)",
    "query": {
     "query": "label_values(falcosecurity_falco_talon_matches_total,source)"
    }
   },
   {
    "name": "priority",
    "label": "priority (match)",
    "query": {
     "query": "label_values(falcosecurity_falco_talon_matches_total{source=~\"$source\"},priority)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace (action)",
    "query": {
     "query": "label_values(falcosecurity_falco_talon_actions_total,namespace)"
    }
   },
   {
    "name": "action_status",
    "label": "status (action)",
    "query": {
     "query": "label_values(falcosecurity_falco_talon_actions_total{namespace=~\"$namespace\"},status)"
    }
   },
   {
    "name": "actionner",
    "query": {
     "query": "label_values(falcosecurity_falco_talon_actions_total{namespace=~\"$namespace\", status=~\"$action_status\"},actionner)"
    }
   },
   {
    "name": "notification_status",
    "label": "status (notification)",
    "query": {
     "query": "label_values(falcosecurity_falco_talon_notifications_total,status)"
    }
   },
   {
    "name": "notifier",
    "query": {
     "query": "label_values(falcosecurity_falco_talon_notifications_total{status=~\"$notification_status\"},notifier)"
    }
   },
   {
    "name": "output_status",
    "label": "output (notification)",
    "query": {
     "query": "label_values(falcosecurity_falco_talon_outputs_total,status)"
    }
   },
   {
    "name": "output",
    "query": {
     "query": "label_values(falcosecurity_falco_talon_outputs_total{status=~\"$output_status\"},target)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Matches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sources",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(source) (increase(falcosecurity_falco_talon_matches_total{source=~\"$source\", priority=~\"$priority\"}[$__rate_interval]))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Rules",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(rule) (increase(falcosecurity_falco_talon_matches_total{priority=~\"$priority\", source=~\"$source\"}[$__rate_interval]))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "Priorities",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(priority) (increase(falcosecurity_falco_talon_matches_total{source=~\"$source\", priority=~\"$priority\"}[$__rate_interval]))",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "title": "by Source over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(source) (increase(falcosecurity_falco_talon_matches_total{source=~\"$source\", priority=~\"$priority\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "by Priority over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(priority) (increase(falcosecurity_falco_talon_matches_total{source=~\"$source\", priority=~\"$priority\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "by Rule over time",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(rule) (increase(falcosecurity_falco_talon_matches_total{source=~\"$source\", priority=~\"$priority\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "last Matches",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(event, source, priority) (increase(falcosecurity_falco_talon_matches_total{source=~\"$source\", priority=~\"$priority\"}[$__rate_interval]))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  { "title": "Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "by Action over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 17, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(action) (increase(falcosecurity_falco_talon_actions_total{namespace=~\"$namespace\", actionner=~\"$actionner\", status=~\"$action_status\"}[$__rate_interval]))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "by Action",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(action) (increase(falcosecurity_falco_talon_actions_total{actionner=~\"$actionner\", namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "by Actionner",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 17, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(actionner) (increase(falcosecurity_falco_talon_actions_total{namespace=~\"$namespace\", actionner=~\"$actionner\"}[$__rate_interval]))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "by Actionner",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(actionner) (increase(falcosecurity_falco_talon_actions_total{actionner=~\"$actionner\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "by Status over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(falcosecurity_falco_talon_actions_total{actionner=~\"$actionner\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "by % Status over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 9, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(falcosecurity_falco_talon_actions_total{actionner=~\"$actionner\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "by Status",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(status) (increase(falcosecurity_falco_talon_actions_total{actionner=~\"$actionner\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "last Actions",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(action, actionner, pod, namespace, rule, status) (increase(falcosecurity_falco_talon_actions_total{actionner=~\"$actionner\", status=~\"$action_status\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  { "title": "Notifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "by Notification over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 17, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(notifier) (increase(falcosecurity_falco_talon_notifications_total{notifier=~\"$notifier\", status=~\"$notification_status\"}[$__rate_interval]))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "by Notifier",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(notifier) (increase(falcosecurity_falco_talon_notifications_total{status=~\"$notification_status\", notifier=~\"$notifier\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "by Status over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(falcosecurity_falco_talon_notifications_total{notifier=~\"$notifier\", status=~\"$notification_status\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "by % Status over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 9, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(falcosecurity_falco_talon_notifications_total{notifier=~\"$notifier\", status=~\"$notification_status\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "by Status",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(status) (increase(falcosecurity_falco_talon_notifications_total{notifier=~\"$notifier\", status=~\"$notification_status\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "last Notifications",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(notifier, status) (increase(falcosecurity_falco_talon_notifications_total{status=~\"$notification_status\", notifier=~\"$notifier\"}[$__rate_interval]))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "Outputs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 },
   "collapsed": true
  },
  {
   "title": "by Output over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 17, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(target) (increase(falcosecurity_falco_talon_outputs_total{target=~\"$output\", status=~\"$output_status\"}[$__rate_interval]))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "by Output",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(target) (increase(falcosecurity_falco_talon_outputs_total{status=~\"$output_status\", target=~\"$output\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "by Status over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(falcosecurity_falco_talon_outputs_total{target=~\"$output\", status=~\"$output_status\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "by % Status over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 9, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(falcosecurity_falco_talon_outputs_total{target=~\"$output\", status=~\"$output_status\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "by Status",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(status) (increase(falcosecurity_falco_talon_outputs_total{target=~\"$output\", status=~\"$output_status\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "last Notifications",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status, target, action, ) (increase(falcosecurity_falco_talon_outputs_total{target=~\"$output\", status=~\"$output_status\"}[$__rate_interval]))",
     "legendFormat": "{{rule}}"
    }
   ]
  }
 ]
}