---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: cpu-stress-order-service
  namespace: apps
spec:
  appinfo:
    appns: apps
    applabel: "app=order-service"
    appkind: deployment
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-cpu-hog
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "120"
            - name: CPU_CORES
              value: "1"
            - name: CPU_LOAD
              value: "100"
            - name: PODS_AFFECTED_PERC
              value: "50"
            - name: CONTAINER_RUNTIME
              value: containerd
            - name: SOCKET_PATH
              value: /run/containerd/containerd.sock
  engineState: active
  annotationCheck: "false"

---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: cpu-stress-inventory-service
  namespace: apps
spec:
  appinfo:
    appns: apps
    applabel: "app=inventory-service"
    appkind: deployment
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-cpu-hog
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "120"
            - name: CPU_CORES
              value: "1"
            - name: CPU_LOAD
              value: "100"
            - name: PODS_AFFECTED_PERC
              value: "50"
            - name: CONTAINER_RUNTIME
              value: containerd
            - name: SOCKET_PATH
              value: /run/containerd/containerd.sock
  engineState: active
  annotationCheck: "false"
