apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: intelliops
  sources:
    - repoURL: https://github.com/nabilpurkar/intelliops-sherlock.git
      path: k8s/helm-charts/kube-prometheus-stack
      targetRevision: main
      helm:
        valueFiles:
          - $values/k8s/helm-values/kube-prometheus-values.yaml
    - repoURL: https://github.com/nabilpurkar/intelliops-sherlock.git
      ref: values
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
