# chart: external-secrets/external-secrets version 2.5.0
# install: helm upgrade --install external-secrets external-secrets/external-secrets --version 2.5.0 -n external-secrets --create-namespace -f external-secrets-values.yaml

installCRDs: true

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: PLACEHOLDER_ESO_ROLE
