# chart: falco/falco
# install: helm upgrade --install falco falco/falco -n falco --create-namespace -f falco-values.yaml

driver:
  kind: modern_ebpf

falcosidekick:
  enabled: true
  webui:
    enabled: true
    redis:
      storageClass: gp2

collectors:
  kubernetes:
    enabled: true
