# chart: linkerd/linkerd-control-plane version 1.16.11
# install: helm upgrade --install linkerd-control-plane linkerd/linkerd-control-plane --version 1.16.11 -n linkerd --create-namespace -f linkerd-control-plane-values.yaml
# Prerequisite: linkerd-crds must be installed first.
# Certs backed up in AWS Secrets Manager: intelliops/dev/linkerd
# Trust anchor valid until: 2036-05-23  |  Issuer valid until: 2027-05-26

controllerLogLevel: info

identityTrustAnchorsPEM: |
  -----BEGIN CERTIFICATE-----
  MIIBjDCCATOgAwIBAgIQV3wAtavscrD1SJn3Cs8XTjAKBggqhkjOPQQDAjAlMSMw
  IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yNjA1MjYyMjE5
  MTBaFw0zNjA1MjMyMjE5MTBaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
  dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+AM2kZVb/F9cSDIA
  b0UFqAWhpl8o9oNB9Cu5JtOUVzt2u3izg73UFtxkw+Q4/mhXwtzdon5vpgxsmvhO
  lrXM9KNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
  VR0OBBYEFONsv8anGe3Nfgmi4IqiVjjcGTVeMAoGCCqGSM49BAMCA0cAMEQCIDAV
  nEDvqkcYtLDq41C2SKfijIG3tAo8+zkg8bfGX2CQAiA/bmvqfMbtESBuuRozQGKy
  rJC1cpSLSsO1q2/DWMJYRA==
  -----END CERTIFICATE-----

identity:
  issuer:
    # scheme: kubernetes.io/tls — Linkerd reads the issuer key+cert from a pre-created
    # Kubernetes Secret named 'linkerd-identity-issuer' in the 'linkerd' namespace.
    # The install script creates that secret from AWS Secrets Manager before this chart is installed.
    scheme: kubernetes.io/tls

proxyInit:
  runAsRoot: true
