portal:
  frontend:
    service:
      type: ClusterIP

  server:
    service:
      type: ClusterIP

    authServer:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi

    graphqlServer:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi

# Use existing secret from AWS Secrets Manager via ExternalSecrets
existingSecret: litmus-mongodb-secret

mongodb:
  # replicaset required so litmus init container rs.status() check passes
  architecture: replicaset
  replicaCount: 1
  persistence:
    storageClass: gp2
    size: 5Gi
  auth:
    existingSecret: litmus-mongodb-secret
  volumePermissions:
    enabled: true
  arbiter:
    enabled: false

adminConfig:
  DBUSER: "admin"
  DB_PORT: "27017"
