# chart: metrics-server/metrics-server version 3.13.0
# install: helm upgrade --install metrics-server k8s/helm-charts/metrics-server -n kube-system -f k8s/helm-values/metrics-server-values.yaml

args:
  - --kubelet-insecure-tls

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
