manager:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  serviceMonitor:
    enabled: false

admissionWebhooks:
  certManager:
    enabled: true
  autoGenerateCert:
    enabled: false
