# chart: open-telemetry/opentelemetry-collector
# install: helm upgrade --install otel-collector open-telemetry/opentelemetry-collector -n monitoring --create-namespace -f otel-collector-values.yaml

mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  exporters:
    prometheus:
      endpoint: 0.0.0.0:8889
    otlphttp/loki:
      endpoint: http://loki.monitoring.svc.cluster.local:3100/otlp
      tls:
        insecure: true
    otlp/tempo:
      endpoint: http://tempo.monitoring.svc.cluster.local:4317
      tls:
        insecure: true

  service:
    pipelines:
      metrics:
        receivers: [otlp]
        exporters: [prometheus]
      logs:
        receivers: [otlp]
        exporters: [otlphttp/loki]
      traces:
        receivers: [otlp]
        exporters: [otlp/tempo]
