# chart: grafana/tempo
# install: helm upgrade --install tempo grafana/tempo -n monitoring --create-namespace -f tempo-values.yaml

persistence:
  enabled: false

tempo:
  reportingEnabled: false

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  metricsGenerator:
    enabled: true
    remoteWriteUrl: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
