apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-github-token
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: backstage-github-token
    creationPolicy: Owner
    template:
      data:
        GITHUB_TOKEN: "{{ .github_token }}"
  dataFrom:
    - extract:
        key: intelliops/dev/backstage
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-postgresql-secret
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: backstage-postgresql-secret
    creationPolicy: Owner
    template:
      data:
        postgresql-password: "{{ .backstage_password }}"
  dataFrom:
    - extract:
        key: intelliops/dev/postgresql
