apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-credentials
    creationPolicy: Owner
    template:
      data:
        admin-user: "admin"
        admin-password: "{{ .admin_password }}"
  dataFrom:
    - extract:
        key: intelliops/dev/grafana
