apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-initdb-scripts
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: postgresql-initdb-scripts
    creationPolicy: Owner
    template:
      engineVersion: "v2"
      data:
        init_sonarqube.sql: |
          CREATE DATABASE sonarqube;
          CREATE USER sonarqube WITH PASSWORD '{{ .sonarqube_password }}';
          GRANT ALL PRIVILEGES ON DATABASE sonarqube TO sonarqube;
          \c sonarqube
          GRANT CREATE ON SCHEMA public TO sonarqube;
        init_defectdojo.sql: |
          CREATE DATABASE defectdojo;
          CREATE USER defectdojo WITH PASSWORD '{{ .defectdojo_password }}';
          GRANT ALL PRIVILEGES ON DATABASE defectdojo TO defectdojo;
          \c defectdojo
          GRANT CREATE ON SCHEMA public TO defectdojo;
        init_kong.sql: |
          CREATE DATABASE kong;
          CREATE USER kong WITH PASSWORD '{{ .kong_password }}';
          GRANT ALL PRIVILEGES ON DATABASE kong TO kong;
          \c kong
          GRANT CREATE ON SCHEMA public TO kong;
        init_backstage.sql: |
          CREATE DATABASE backstage;
          CREATE USER backstage WITH PASSWORD '{{ .backstage_password }}';
          GRANT ALL PRIVILEGES ON DATABASE backstage TO backstage;
          \c backstage
          GRANT CREATE ON SCHEMA public TO backstage;
  dataFrom:
    - extract:
        key: intelliops/dev/postgresql
