apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-credentials
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: postgresql-credentials
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: intelliops/dev/postgresql
        property: postgres_password
    - secretKey: sonarqube-password
      remoteRef:
        key: intelliops/dev/postgresql
        property: sonarqube_password
    - secretKey: kong-password
      remoteRef:
        key: intelliops/dev/postgresql
        property: kong_password
