apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-initdb-scripts
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: postgresql-initdb-scripts
    creationPolicy: Owner
    template:
      data:
        init.sql: |
          CREATE DATABASE sonarqube;
          CREATE USER sonarqube WITH PASSWORD '{{ .sonarqube_password }}';
          GRANT ALL PRIVILEGES ON DATABASE sonarqube TO sonarqube;

          CREATE DATABASE defectdojo;
          CREATE USER defectdojo WITH PASSWORD '{{ .defectdojo_password }}';
          GRANT ALL PRIVILEGES ON DATABASE defectdojo TO defectdojo;

          CREATE DATABASE kong;
          CREATE USER kong WITH PASSWORD '{{ .kong_password }}';
          GRANT ALL PRIVILEGES ON DATABASE kong TO kong;
  dataFrom:
    - extract:
        key: intelliops/dev/postgresql
