apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-webhook
  namespace: aiops-demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: slack-webhook
    creationPolicy: Owner
    template:
      data:
        SLACK_WEBHOOK_URL: "{{ .webhook_url }}"
  dataFrom:
    - extract:
        key: intelliops/dev/slack
