apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-credentials
  namespace: sonarqube
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: postgresql-credentials
    creationPolicy: Owner
  data:
    - secretKey: sonarqube-password
      remoteRef:
        key: intelliops/dev/postgresql
        property: sonarqube_password
    - secretKey: monitoring-passcode
      remoteRef:
        key: intelliops/dev/postgresql
        property: sonarqube_monitoring_passcode
