---
# ServiceMonitor — scrape Kyverno admission controller metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kyverno-admission
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - kyverno
  selector:
    matchLabels:
      app.kubernetes.io/name: kyverno-admission-controller
  endpoints:
    - port: metrics-port
      interval: 30s
      path: /metrics
---
# ServiceMonitor — scrape Kyverno background controller metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kyverno-background
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - kyverno
  selector:
    matchLabels:
      app.kubernetes.io/name: kyverno-background-controller
  endpoints:
    - port: metrics-port
      interval: 30s
      path: /metrics
---
# ServiceMonitor — scrape Kyverno reports controller metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kyverno-reports
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - kyverno
  selector:
    matchLabels:
      app.kubernetes.io/name: kyverno-reports-controller
  endpoints:
    - port: metrics-port
      interval: 30s
      path: /metrics
