apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: intelliops
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  description: IntelliOps Sherlock — AIOps demo platform

  sourceRepos:
    - https://github.com/nabilpurkar/intelliops-sherlock.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: apps
    - server: https://kubernetes.default.svc
      namespace: locust
    - server: https://kubernetes.default.svc
      namespace: aiops-demo

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "apps"
      kind: Deployment
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: ConfigMap
    - group: "autoscaling"
      kind: HorizontalPodAutoscaler
    - group: "batch"
      kind: CronJob
    - group: "rbac.authorization.k8s.io"
      kind: Role
    - group: "rbac.authorization.k8s.io"
      kind: RoleBinding
    - group: "monitoring.coreos.com"
      kind: ServiceMonitor
