apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: aiops-demo
  labels:
    app: inventory-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port:   "8001"
    prometheus.io/path:   "/metrics"
spec:
  type: ClusterIP
  selector:
    app: inventory-service
  ports:
    - name: http
      port:       8001
      targetPort: 8001
      protocol:   TCP

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service-headless
  namespace: aiops-demo
  labels:
    app: inventory-service
spec:
  clusterIP: None
  selector:
    app: inventory-service
  ports:
    - name: http
      port:       8001
      targetPort: 8001
